-- AlterTable
ALTER TABLE "consultancies" ALTER COLUMN "selectedYear" SET DEFAULT EXTRACT(YEAR FROM CURRENT_DATE);

-- AlterTable
ALTER TABLE "users" ALTER COLUMN "selectedYear" SET DEFAULT EXTRACT(YEAR FROM CURRENT_DATE);
